/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariojoyeriapoo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Sara.Reyna
 * Nohemi Ramos
 * Eda Nolasco
 */
public class CompraInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form CompraInterfaz
     */
    public CompraInterfaz() {
        initComponents();
        jScrollPane2.setVisible(false);
        CantidadTF.setVisible(false);
        cargarTabla();
        this.setLocationRelativeTo(null);
    }
    
    String url = "jdbc:mysql://localhost:3306/inventario_joyeria";
    String username = "root";
    //String password = "Lechedefresa";
    String password = "$usanA198";
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    int ViejaCantidad; 
    
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel)Compras.getModel();
        modeloTabla.setRowCount(0);
        
        int columnas;
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT * FROM compras"); 
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }    
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Compras = new javax.swing.JTable();
        JLabelNomCliCom = new javax.swing.JLabel();
        JLabelCanCom = new javax.swing.JLabel();
        JLabelFechaCom = new javax.swing.JLabel();
        JtexCantCom = new javax.swing.JTextField();
        JtexFechaCom = new javax.swing.JTextField();
        JtexIDPro = new javax.swing.JTextField();
        BotonEliminarCom = new javax.swing.JButton();
        BotonEditarCom = new javax.swing.JButton();
        TFIDCompra = new javax.swing.JTextField();
        LaberIDCompra = new javax.swing.JLabel();
        CantidadTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Compras1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuInventario = new javax.swing.JMenu();
        ItemLista_Productos = new javax.swing.JMenuItem();
        jMenuCompra = new javax.swing.JMenu();
        Item_Lista_Compras = new javax.swing.JMenuItem();
        Item_RegistrarCompra = new javax.swing.JMenuItem();
        ItemNuevo_Producto = new javax.swing.JMenuItem();
        jMenuPedidos = new javax.swing.JMenu();
        ITem_Lista_Pedidos = new javax.swing.JMenuItem();
        Item_AgregarPedido = new javax.swing.JMenuItem();
        jMenuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPanel2.setBackground(new java.awt.Color(194, 193, 242));

        Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Cliente", "Cantidad", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Compras);

        JLabelNomCliCom.setText("ID del producto");

        JLabelCanCom.setText("Cantidad");

        JLabelFechaCom.setText("Fecha");

        BotonEliminarCom.setBackground(new java.awt.Color(248, 206, 204));
        BotonEliminarCom.setText("Eliminar");
        BotonEliminarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarComActionPerformed(evt);
            }
        });

        BotonEditarCom.setBackground(new java.awt.Color(255, 242, 204));
        BotonEditarCom.setText("Guardar cambios");
        BotonEditarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarComActionPerformed(evt);
            }
        });

        LaberIDCompra.setText("ID de compra");

        CantidadTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadTFActionPerformed(evt);
            }
        });

        Compras1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cantidad anterior"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Compras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Compras1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Compras1);

        javax.swing.GroupLayout JPanel2Layout = new javax.swing.GroupLayout(JPanel2);
        JPanel2.setLayout(JPanel2Layout);
        JPanel2Layout.setHorizontalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel2Layout.createSequentialGroup()
                                .addComponent(LaberIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(TFIDCompra))
                            .addGroup(JPanel2Layout.createSequentialGroup()
                                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabelCanCom)
                                    .addComponent(JLabelFechaCom)
                                    .addComponent(JLabelNomCliCom))
                                .addGap(37, 37, 37)
                                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtexIDPro)
                                    .addComponent(JtexFechaCom)
                                    .addComponent(JtexCantCom))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                                .addComponent(BotonEliminarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonEditarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        JPanel2Layout.setVerticalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanel2Layout.createSequentialGroup()
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LaberIDCompra)
                            .addComponent(TFIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelNomCliCom)
                            .addComponent(JtexIDPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelCanCom)
                            .addComponent(JtexCantCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtexFechaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelFechaCom))
                        .addGap(59, 59, 59)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonEditarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEliminarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jMenuInventario.setText("Inventario");

        ItemLista_Productos.setText("Lista de productos");
        ItemLista_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemLista_ProductosActionPerformed(evt);
            }
        });
        jMenuInventario.add(ItemLista_Productos);

        jMenuBar2.add(jMenuInventario);

        jMenuCompra.setText("Compra");

        Item_Lista_Compras.setText("Listas de Compras");
        Item_Lista_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Lista_ComprasActionPerformed(evt);
            }
        });
        jMenuCompra.add(Item_Lista_Compras);

        Item_RegistrarCompra.setText("Registrar nueva compra");
        Item_RegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_RegistrarCompraActionPerformed(evt);
            }
        });
        jMenuCompra.add(Item_RegistrarCompra);

        ItemNuevo_Producto.setText("Agregar nuevo producto");
        ItemNuevo_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNuevo_ProductoActionPerformed(evt);
            }
        });
        jMenuCompra.add(ItemNuevo_Producto);

        jMenuBar2.add(jMenuCompra);

        jMenuPedidos.setText("Pedidos");

        ITem_Lista_Pedidos.setText("Lista de pedidos");
        ITem_Lista_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITem_Lista_PedidosActionPerformed(evt);
            }
        });
        jMenuPedidos.add(ITem_Lista_Pedidos);

        Item_AgregarPedido.setText("Agregar Pedido");
        Item_AgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_AgregarPedidoActionPerformed(evt);
            }
        });
        jMenuPedidos.add(Item_AgregarPedido);

        jMenuBar2.add(jMenuPedidos);

        jMenuCerrarSesion.setText("Cerrar Sesion");
        jMenuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCerrarSesionMouseClicked(evt);
            }
        });
        jMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarSesionActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenuCerrarSesion);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemLista_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemLista_ProductosActionPerformed
        Inventario in = new Inventario();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_ItemLista_ProductosActionPerformed

    private void Item_RegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_RegistrarCompraActionPerformed
        RegistrarCompra NewCompra = new RegistrarCompra();
        NewCompra.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_RegistrarCompraActionPerformed

    private void ItemNuevo_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNuevo_ProductoActionPerformed
        AgregarProducto NewProd = new AgregarProducto();
        NewProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_ItemNuevo_ProductoActionPerformed

    private void ITem_Lista_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITem_Lista_PedidosActionPerformed
        Pedidos PD = new Pedidos();
        PD.setVisible(true);
        dispose();
    }//GEN-LAST:event_ITem_Lista_PedidosActionPerformed

    private void Item_AgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_AgregarPedidoActionPerformed
        AgregarPedido AP = new AgregarPedido();
        AP.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_AgregarPedidoActionPerformed

    private void jMenuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCerrarSesionMouseClicked
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCerrarSesionMouseClicked

    private void jMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarSesionActionPerformed
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCerrarSesionActionPerformed

    private void BotonEliminarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarComActionPerformed
        int id = Integer.parseInt(TFIDCompra.getText());
        
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("DELETE FROM compras WHERE id_c=?");
            ps.setInt(1, id);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Pedido eliminado");
            cargarTabla();
            TFIDCompra.setText("");
            JtexIDPro.setText("");
            JtexCantCom.setText("");
            JtexFechaCom.setText("");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_BotonEliminarComActionPerformed

    private void Item_Lista_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Lista_ComprasActionPerformed
        CompraInterfaz CI = new CompraInterfaz();
        CI.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_Lista_ComprasActionPerformed

    private void ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasMouseClicked
        try{
            int fila = Compras.getSelectedRow();
            int id= Integer.parseInt(Compras.getValueAt(fila, 0).toString());
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT id_c, id_pr,cantidad,fecha FROM compras where id_c=?"); 
            ps.setInt(1, id);
            rs = ps.executeQuery();
            
            while(rs.next()){
                TFIDCompra.setText(rs.getString("id_c"));
                TFIDCompra.setEditable(false);
                TFIDCompra.setEnabled(false);
                
                JtexIDPro.setText(rs.getString("id_pr"));
                JtexCantCom.setText(rs.getString("cantidad"));
                JtexFechaCom.setText(rs.getString("fecha"));
            }
            ViejaCantidad = Integer.parseInt( JtexCantCom.getText());
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_ComprasMouseClicked
    
    private void cargarInventario(int IDProducto){
       DefaultTableModel modeloTabla = (DefaultTableModel)Compras1.getModel();
       modeloTabla.setRowCount(0);
       
       int columnas;
       try{
           Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?");
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i<columnas; i++){
                    fila[i] =rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
       }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
       }  
   }
    
    private void cargarViejaCantidad(int IDProducto){
        try{
            cargarInventario(IDProducto);
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?"); 
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            
            while(rs.next()){
                CantidadTF.setText(rs.getString("stock"));
                CantidadTF.setEditable(false);
                CantidadTF.setEnabled(false);
                CantidadTF.setVisible(false);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
   }
    private void actualizarInventario(int IDProducto, int Cantidad){
       try{
           cargarViejaCantidad(IDProducto);
           
            Connection connection = DriverManager.getConnection(url,username,password);
            int actualI = Integer.parseInt( CantidadTF.getText());
            
            int antiguaI, nuevaI;
            antiguaI = actualI - ViejaCantidad;
            nuevaI= antiguaI + Cantidad;
            
            ps= connection.prepareStatement("update inventario set stock= ? where id_pr = ?");
            ps.setInt(1, nuevaI);
            ps.setInt(2, IDProducto);
            ps.executeUpdate();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }  
   }
    private void BotonEditarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarComActionPerformed
        int id = Integer.parseInt(TFIDCompra.getText());
        /*****************************************/
        int IDProducto = Integer.parseInt(JtexIDPro.getText());
        int Cantidad = Integer.parseInt(JtexCantCom.getText());
        String fecha= JtexFechaCom.getText();
        
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("UPDATE compras SET id_pr=?,cantidad=?, fecha=? WHERE id_c = ?");
            ps.setInt(1, IDProducto);
            ps.setInt(2, Cantidad);
            ps.setString(3, fecha);
            ps.setInt(4, id);
            ps.executeUpdate();
            
            /***********************************************************************************/
            actualizarInventario(IDProducto,Cantidad);
            
            /**************************************************************************************/
            JOptionPane.showMessageDialog(null, "Registro de compra modificada");
            cargarTabla();
            TFIDCompra.setText("");
            JtexIDPro.setText("");
            JtexCantCom.setText("");
            JtexFechaCom.setText("");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }      
    }//GEN-LAST:event_BotonEditarComActionPerformed

    private void CantidadTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadTFActionPerformed

    private void Compras1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Compras1MouseClicked

    }//GEN-LAST:event_Compras1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEditarCom;
    private javax.swing.JButton BotonEliminarCom;
    private javax.swing.JTextField CantidadTF;
    private javax.swing.JTable Compras;
    private javax.swing.JTable Compras1;
    private javax.swing.JMenuItem ITem_Lista_Pedidos;
    private javax.swing.JMenuItem ItemLista_Productos;
    private javax.swing.JMenuItem ItemNuevo_Producto;
    private javax.swing.JMenuItem Item_AgregarPedido;
    private javax.swing.JMenuItem Item_Lista_Compras;
    private javax.swing.JMenuItem Item_RegistrarCompra;
    private javax.swing.JLabel JLabelCanCom;
    private javax.swing.JLabel JLabelFechaCom;
    private javax.swing.JLabel JLabelNomCliCom;
    private javax.swing.JPanel JPanel2;
    private javax.swing.JTextField JtexCantCom;
    private javax.swing.JTextField JtexFechaCom;
    private javax.swing.JTextField JtexIDPro;
    private javax.swing.JLabel LaberIDCompra;
    private javax.swing.JTextField TFIDCompra;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCerrarSesion;
    private javax.swing.JMenu jMenuCompra;
    private javax.swing.JMenu jMenuInventario;
    private javax.swing.JMenu jMenuPedidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
