/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariojoyeriapoo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sara.Reyna
 */
public class CompraInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form CompraInterfaz
     */
    public CompraInterfaz() {
        initComponents();
        cargarTabla();
        this.setLocationRelativeTo(null);
    }
    
    String url = "jdbc:mysql://localhost:3306/inventario_joyeria";
    String username = "root";
    //String password = "Lechedefresa";
    String password = "$usanA198";
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    int ViejaCantidad; 
    
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel)Compras.getModel();
        modeloTabla.setRowCount(0);
        
        int columnas;
        try{
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT * FROM compras"); 
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
                   
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Compras = new javax.swing.JTable();
        JLabelNomCliCom = new javax.swing.JLabel();
        JLabelCanCom = new javax.swing.JLabel();
        JLabelFechaCom = new javax.swing.JLabel();
        JtexCantCom = new javax.swing.JTextField();
        JtexFechaCom = new javax.swing.JTextField();
        JtexIDPro = new javax.swing.JTextField();
        BotonEliminarCom = new javax.swing.JButton();
        BotonEditarCom = new javax.swing.JButton();
        TFIDCompra = new javax.swing.JTextField();
        LaberIDCompra = new javax.swing.JLabel();
        CantidadTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Compras1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPanel2.setBackground(new java.awt.Color(194, 193, 242));

        Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Cliente", "Cantidad", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Compras);

        JLabelNomCliCom.setText("ID del producto");

        JLabelCanCom.setText("Cantidad");

        JLabelFechaCom.setText("Fecha");

        JtexCantCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtexCantComActionPerformed(evt);
            }
        });

        BotonEliminarCom.setBackground(new java.awt.Color(248, 206, 204));
        BotonEliminarCom.setText("Eliminar");
        BotonEliminarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarComActionPerformed(evt);
            }
        });

        BotonEditarCom.setBackground(new java.awt.Color(255, 242, 204));
        BotonEditarCom.setText("Editar");
        BotonEditarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarComActionPerformed(evt);
            }
        });

        LaberIDCompra.setText("ID de compra");

        CantidadTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadTFActionPerformed(evt);
            }
        });

        Compras1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cantidad anterior"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Compras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Compras1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Compras1);

        javax.swing.GroupLayout JPanel2Layout = new javax.swing.GroupLayout(JPanel2);
        JPanel2.setLayout(JPanel2Layout);
        JPanel2Layout.setHorizontalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel2Layout.createSequentialGroup()
                                .addComponent(LaberIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(TFIDCompra))
                            .addGroup(JPanel2Layout.createSequentialGroup()
                                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabelCanCom)
                                    .addComponent(JLabelFechaCom))
                                .addGap(73, 73, 73)
                                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtexFechaCom)
                                    .addComponent(JtexCantCom)))
                            .addGroup(JPanel2Layout.createSequentialGroup()
                                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonEliminarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelNomCliCom))
                                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(JtexIDPro))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonEditarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        JPanel2Layout.setVerticalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LaberIDCompra)
                            .addComponent(TFIDCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelNomCliCom)
                            .addComponent(JtexIDPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelCanCom)
                            .addComponent(JtexCantCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtexFechaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelFechaCom))
                        .addGap(49, 49, 49)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonEliminarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEditarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel2Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jMenu1.setText("Inventario");

        jMenuItem13.setText("Eliminar Producto");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuBar2.add(jMenu1);

        jMenu3.setText("Compra");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem17.setText("Listas de Compras");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem18.setText("Registrar nueva compra");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem19.setText("Agregar nuevo producto");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuBar2.add(jMenu3);

        jMenu2.setText("Pedidos");

        jMenuItem14.setText("Lista de pedidos");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Agregar Pedido");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar2.add(jMenu2);

        jMenu4.setText("Cerrar Sesion");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        RegistrarCompra NewCompra = new RegistrarCompra();
        NewCompra.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        AgregarProducto NewProd = new AgregarProducto();
        NewProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        Pedidos PD = new Pedidos();
        PD.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        AgregarCompra AP = new AgregarCompra();
        AP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void JtexCantComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtexCantComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtexCantComActionPerformed

    private void BotonEliminarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarComActionPerformed
        int id = Integer.parseInt(TFIDCompra.getText());
        
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("DELETE FROM compras WHERE id_c=?");
            ps.setInt(1, id);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Pedido eliminado");
            cargarTabla();
            TFIDCompra.setText("");
            JtexIDPro.setText("");
            JtexCantCom.setText("");
            JtexFechaCom.setText("");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_BotonEliminarComActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        CompraInterfaz CI = new CompraInterfaz();
        CI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasMouseClicked
        // TODO add your handling code here:
        try{
            int fila = Compras.getSelectedRow();
            int id= Integer.parseInt(Compras.getValueAt(fila, 0).toString());
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT id_c, id_pr,cantidad,fecha FROM compras where id_c=?"); 
            ps.setInt(1, id);
            rs = ps.executeQuery();
            
            while(rs.next()){
                TFIDCompra.setText(rs.getString("id_c"));
                TFIDCompra.setEditable(false);
                TFIDCompra.setEnabled(false);
                
                JtexIDPro.setText(rs.getString("id_pr"));
                JtexCantCom.setText(rs.getString("cantidad"));
                JtexFechaCom.setText(rs.getString("fecha"));
            }
            ViejaCantidad = Integer.parseInt( JtexCantCom.getText());
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_ComprasMouseClicked
    
    private void cargarInventario(int IDProducto){
       DefaultTableModel modeloTabla = (DefaultTableModel)Compras1.getModel();
       modeloTabla.setRowCount(0);
       
       int columnas;
       try{
           Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?");
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i<columnas; i++){
                    fila[i] =rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
             
            //pasar estas dos ultimas lineas a otro metodo para poder 
            //despues llamar en el que estamos ahorita y asi re guardar 
            //lo que tenemos en la vieja cantidad
            //int f = Compras.getSelectedRow();
            //ViejaCantidad = Integer.parseInt(Compras.getValueAt(f, 0).toString());
            
       }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
       }  
   }
    
    private void cargarViejaCantidad(int IDProducto){
       
        try{
            int fila = Compras1.getSelectedRow();
            cargarInventario(IDProducto);
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?"); 
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            
            while(rs.next()){
                CantidadTF.setText(rs.getString("stock"));
                CantidadTF.setEditable(false);
                CantidadTF.setEnabled(false);
                CantidadTF.setVisible(false);
            }
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
   }
    private void actualizarInventario(int IDProducto, int Cantidad){
       try{
           //cargarInventario(IDProducto);
            Connection connection = DriverManager.getConnection(url,username,password);
            //ViejaCantidad 
            int actualI = Integer.parseInt( CantidadTF.getText());
            
            int antiguaI=0, nuevaI=0;
            
            antiguaI = actualI - ViejaCantidad;
            nuevaI= antiguaI + Cantidad;
/* 
            ViejaCantidad= la cantidad que se compro por lo que es lo que se sumo a inventario
            NuevaCantidad = lo que se modifico en compras 
            
            
            antiguaI = a lo que tenia inventario antes de la compra
            actualI = lo que tiene ahora inventario esto hay que sacarlo de otra funcion
            
            nuevaI = lo que vamos a cambiar en  inventario 
            */
            ps= connection.prepareStatement("update inventario set stock= ? where id_pr = ?");
            ps.setInt(1, nuevaI);
            ps.setInt(2, IDProducto);
            ps.executeUpdate();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }  
       
   }
    private void BotonEditarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarComActionPerformed
        int id = Integer.parseInt(TFIDCompra.getText());
        /*****************************************/
        int IDProducto = Integer.parseInt(JtexIDPro.getText());
        int Cantidad = Integer.parseInt(JtexCantCom.getText());
        String fecha= JtexFechaCom.getText();
        
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("UPDATE compras SET id_pr=?,cantidad=?, fecha=? WHERE id_c = ?");
            ps.setInt(1, IDProducto);
            ps.setInt(2, Cantidad);
            ps.setString(3, fecha);
            ps.setInt(4, id);
            ps.executeUpdate();
            
            /***********************************************************************************/
            actualizarInventario(IDProducto,Cantidad);
            
            /**************************************************************************************/
            JOptionPane.showMessageDialog(null, "Registro de compra modificada");
            cargarTabla();
            TFIDCompra.setText("");
            JtexIDPro.setText("");
            JtexCantCom.setText("");
            JtexFechaCom.setText("");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }      
        
        
    }//GEN-LAST:event_BotonEditarComActionPerformed

    private void CantidadTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadTFActionPerformed

    private void Compras1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Compras1MouseClicked

    }//GEN-LAST:event_Compras1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEditarCom;
    private javax.swing.JButton BotonEliminarCom;
    private javax.swing.JTextField CantidadTF;
    private javax.swing.JTable Compras;
    private javax.swing.JTable Compras1;
    private javax.swing.JLabel JLabelCanCom;
    private javax.swing.JLabel JLabelFechaCom;
    private javax.swing.JLabel JLabelNomCliCom;
    private javax.swing.JPanel JPanel2;
    private javax.swing.JTextField JtexCantCom;
    private javax.swing.JTextField JtexFechaCom;
    private javax.swing.JTextField JtexIDPro;
    private javax.swing.JLabel LaberIDCompra;
    private javax.swing.JTextField TFIDCompra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
