/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariojoyeriapoo;

/**
 *
 * @author Sara.Reyna
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPrincipal = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        LabelContra = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        TFContra = new javax.swing.JTextField();
        BotonListo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(194, 196, 242));
        setBounds(new java.awt.Rectangle(200, 200, 200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelPrincipal.setText("INICIO DE SESION");
        getContentPane().add(LabelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 45, 107, -1));

        LabelUsuario.setText("Usuario");
        getContentPane().add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 104, 57, -1));

        LabelContra.setText("Contraseña: ");
        getContentPane().add(LabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 144, -1, -1));
        getContentPane().add(TFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 101, 130, -1));
        getContentPane().add(TFContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 141, 130, -1));

        BotonListo.setBackground(new java.awt.Color(113, 118, 217));
        BotonListo.setText("Listo");
        BotonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 209, 75, -1));

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(194, 196, 242));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 360, 260);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonListo;
    private javax.swing.JLabel LabelContra;
    private javax.swing.JLabel LabelPrincipal;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JTextField TFContra;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
