/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariojoyeriapoo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.ResultSetMetaData;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Eda Nolasco
 * Sara Reyna 
 * Nohemi Ramos
 */
public class Inventario extends javax.swing.JFrame {
    //**************ATRIBUTOS*****************
    String url = "jdbc:mysql://localhost:3306/inventario_joyeria";
    String username = "root";
    //String password = "Lechedefresa";
    String password = "$usanA198";
    
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    //***************FIN ATRIBUTOS***********************
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
    }
    
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel)Inventario.getModel();
        modeloTabla.setRowCount(0);
        int columnas;
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT * FROM inventario");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
                   
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Inventario = new javax.swing.JTable();
        botonEliminarInventario = new javax.swing.JButton();
        MostrarID = new javax.swing.JTextField();
        Productos = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Stock = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        JMenuInventario = new javax.swing.JMenu();
        MenuItem_ListaProductos = new javax.swing.JMenuItem();
        JMenuCompra = new javax.swing.JMenu();
        MenuItem_ListaCompras = new javax.swing.JMenuItem();
        MenuItem_RegistrarCompra = new javax.swing.JMenuItem();
        MenuItem_AgregarProducto = new javax.swing.JMenuItem();
        JMenuPedidos = new javax.swing.JMenu();
        MenuItem_ListaPedidos = new javax.swing.JMenuItem();
        MenuItem_AgregarPedido = new javax.swing.JMenuItem();
        JMenu_CerrarSesion = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem16.setText("jMenuItem16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(194, 196, 242));

        Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Productos", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Inventario);

        botonEliminarInventario.setBackground(new java.awt.Color(248, 206, 204));
        botonEliminarInventario.setText("Eliminar");
        botonEliminarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarInventarioActionPerformed(evt);
            }
        });

        Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockActionPerformed(evt);
            }
        });

        jLabel1.setText("ID PRODUCTO");

        jLabel2.setText("PRODUCTO");

        jLabel3.setText("PRECIO");

        jLabel4.setText("STOCK");

        botonBuscar.setBackground(new java.awt.Color(51, 204, 255));
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonLimpiar.setBackground(new java.awt.Color(102, 102, 255));
        botonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Precio)
                            .addComponent(Stock)
                            .addComponent(Productos)
                            .addComponent(MostrarID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(botonEliminarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEliminarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        JMenuInventario.setText("Inventario");

        MenuItem_ListaProductos.setText("Lista de Productos");
        MenuItem_ListaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ListaProductosActionPerformed(evt);
            }
        });
        JMenuInventario.add(MenuItem_ListaProductos);

        jMenuBar2.add(JMenuInventario);

        JMenuCompra.setText("Compra");

        MenuItem_ListaCompras.setText("Listas de Compras");
        MenuItem_ListaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ListaComprasActionPerformed(evt);
            }
        });
        JMenuCompra.add(MenuItem_ListaCompras);

        MenuItem_RegistrarCompra.setText("Registrar nueva compra");
        MenuItem_RegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_RegistrarCompraActionPerformed(evt);
            }
        });
        JMenuCompra.add(MenuItem_RegistrarCompra);

        MenuItem_AgregarProducto.setText("Agregar nuevo producto");
        MenuItem_AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_AgregarProductoActionPerformed(evt);
            }
        });
        JMenuCompra.add(MenuItem_AgregarProducto);

        jMenuBar2.add(JMenuCompra);

        JMenuPedidos.setText("Pedidos");

        MenuItem_ListaPedidos.setText("Lista de pedidos");
        MenuItem_ListaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ListaPedidosActionPerformed(evt);
            }
        });
        JMenuPedidos.add(MenuItem_ListaPedidos);

        MenuItem_AgregarPedido.setText("Agregar Pedido");
        MenuItem_AgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_AgregarPedidoActionPerformed(evt);
            }
        });
        JMenuPedidos.add(MenuItem_AgregarPedido);

        jMenuBar2.add(JMenuPedidos);

        JMenu_CerrarSesion.setText("Cerrar Sesion");
        JMenu_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenu_CerrarSesionMouseClicked(evt);
            }
        });
        JMenu_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_CerrarSesionActionPerformed(evt);
            }
        });
        jMenuBar2.add(JMenu_CerrarSesion);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_ListaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ListaProductosActionPerformed
        Inventario in = new Inventario();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuItem_ListaProductosActionPerformed

    private void MenuItem_ListaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ListaComprasActionPerformed
        CompraInterfaz CI = new CompraInterfaz();
        CI.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuItem_ListaComprasActionPerformed

    private void MenuItem_RegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_RegistrarCompraActionPerformed
        RegistrarCompra NewCompra = new RegistrarCompra();
        NewCompra.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuItem_RegistrarCompraActionPerformed

    private void MenuItem_AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_AgregarProductoActionPerformed
        AgregarProducto NewProd = new AgregarProducto();
        NewProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuItem_AgregarProductoActionPerformed

    private void MenuItem_ListaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ListaPedidosActionPerformed
        Pedidos PD = new Pedidos();
        PD.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuItem_ListaPedidosActionPerformed

    private void MenuItem_AgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_AgregarPedidoActionPerformed
        AgregarPedido AP = new AgregarPedido();
        AP.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuItem_AgregarPedidoActionPerformed

    private void JMenu_CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_CerrarSesionMouseClicked
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_JMenu_CerrarSesionMouseClicked

    private void JMenu_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_CerrarSesionActionPerformed
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_JMenu_CerrarSesionActionPerformed

    private void InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioMouseClicked
        try{
            int fila = Inventario.getSelectedRow();
            int id = Integer.parseInt(Inventario.getValueAt(fila, 0).toString());
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT  productos, precio, stock FROM inventario WHERE id_pr=?");
            ps.setInt(1,id);
            rs = ps.executeQuery();
            while(rs.next()){
                MostrarID.setText(String.valueOf(id));
                Productos.setText(rs.getString("productos"));
                Precio.setText(rs.getString("precio"));
                Stock.setText(rs.getString("stock"));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_InventarioMouseClicked

    private void botonEliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarInventarioActionPerformed
            int id = Integer.parseInt(MostrarID.getText());
            try {
                Connection connection = DriverManager.getConnection(url,username,password);

                ps= connection.prepareStatement("DELETE FROM inventario WHERE id_pr=?");
                ps.setInt(1, id);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Producto eliminado");
                cargarTabla();//funcion para mostrar la tabla
                
                MostrarID.setText("");
                Productos.setText("");
                Precio.setText("");
                Stock.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex.toString());
            }

    }//GEN-LAST:event_botonEliminarInventarioActionPerformed

    private void StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel)Inventario.getModel();
        modeloTabla.setRowCount(0);
        
        int columnas;
        int id = Integer.parseInt(MostrarID.getText());
        String nomProducto = Productos.getText();
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT * FROM inventario WHERE id_pr =? or productos= ?");
            ps.setInt(1, id);
            ps.setString(2, nomProducto);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        cargarTabla();
        MostrarID.setText("");
        Productos.setText("");
        Precio.setText("");
        Stock.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Inventario;
    private javax.swing.JMenu JMenuCompra;
    private javax.swing.JMenu JMenuInventario;
    private javax.swing.JMenu JMenuPedidos;
    private javax.swing.JMenu JMenu_CerrarSesion;
    private javax.swing.JMenuItem MenuItem_AgregarPedido;
    private javax.swing.JMenuItem MenuItem_AgregarProducto;
    private javax.swing.JMenuItem MenuItem_ListaCompras;
    private javax.swing.JMenuItem MenuItem_ListaPedidos;
    private javax.swing.JMenuItem MenuItem_ListaProductos;
    private javax.swing.JMenuItem MenuItem_RegistrarCompra;
    private javax.swing.JTextField MostrarID;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextField Productos;
    private javax.swing.JTextField Stock;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminarInventario;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
