/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariojoyeriapoo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Eda Nolasco 
 * Nohemi Ramos
 * Sara Reyna
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        cargarTabla();
        this.setLocationRelativeTo(null);
        jScrollPane2.setVisible(false);
        CantidadTF.setVisible(false);
        Pedidos.setDefaultRenderer(Object.class,new PedidosClass());
    }
     //**********************************************************
    int ViejaCantidad;
    String url = "jdbc:mysql://localhost:3306/inventario_joyeria";
    String username = "root";
    //String password = "Lechedefresa";
    String password = "$usanA198";
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    //**********************************************************
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel)Pedidos.getModel();
        modeloTabla.setRowCount(0);
        int columnas;
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT * FROM pedidos");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDPedido = new javax.swing.JTextField();
        ClientePedido = new javax.swing.JTextField();
        IDProducto = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();
        Completar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Compras1 = new javax.swing.JTable();
        CantidadTF = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        JMenu_Inventario = new javax.swing.JMenu();
        Item_Lista_Productos = new javax.swing.JMenuItem();
        jMenu_Compra = new javax.swing.JMenu();
        Item_Lista_Compras = new javax.swing.JMenuItem();
        Item_Registrar_Compra = new javax.swing.JMenuItem();
        Item_Agregar_Producto = new javax.swing.JMenuItem();
        jMenu_Pedidos = new javax.swing.JMenu();
        Item_Lista_Pedidos = new javax.swing.JMenuItem();
        Item_AgregarPedido = new javax.swing.JMenuItem();
        jMenu_Cerrar_Sesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(194, 196, 242));

        Pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Cliente", "ID Producto", "Cantidad", "Fecha", "Completado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Pedidos);

        jLabel1.setText("ID");

        jLabel2.setText("Nombre del cliente");

        jLabel3.setText("ID Producto");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Fecha");

        Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(248, 206, 204));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Completar.setBackground(new java.awt.Color(213, 232, 212));
        Completar.setText("Completar");
        Completar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompletarActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 242, 204));
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Compras1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cantidad anterior"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Compras1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(IDPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ClientePedido)
                                    .addComponent(IDProducto)
                                    .addComponent(Cantidad)
                                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Completar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Completar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JMenu_Inventario.setText("Inventario");

        Item_Lista_Productos.setText("Lista de Productos");
        Item_Lista_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Lista_ProductosActionPerformed(evt);
            }
        });
        JMenu_Inventario.add(Item_Lista_Productos);

        jMenuBar2.add(JMenu_Inventario);

        jMenu_Compra.setText("Compra");

        Item_Lista_Compras.setText("Listas de Compras");
        Item_Lista_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Lista_ComprasActionPerformed(evt);
            }
        });
        jMenu_Compra.add(Item_Lista_Compras);

        Item_Registrar_Compra.setText("Registrar nueva compra");
        Item_Registrar_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Registrar_CompraActionPerformed(evt);
            }
        });
        jMenu_Compra.add(Item_Registrar_Compra);

        Item_Agregar_Producto.setText("Agregar nuevo producto");
        Item_Agregar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Agregar_ProductoActionPerformed(evt);
            }
        });
        jMenu_Compra.add(Item_Agregar_Producto);

        jMenuBar2.add(jMenu_Compra);

        jMenu_Pedidos.setText("Pedidos");
        jMenu_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_PedidosActionPerformed(evt);
            }
        });

        Item_Lista_Pedidos.setText("Lista de pedidos");
        Item_Lista_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Lista_PedidosActionPerformed(evt);
            }
        });
        jMenu_Pedidos.add(Item_Lista_Pedidos);

        Item_AgregarPedido.setText("Agregar Pedido");
        Item_AgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_AgregarPedidoActionPerformed(evt);
            }
        });
        jMenu_Pedidos.add(Item_AgregarPedido);

        jMenuBar2.add(jMenu_Pedidos);

        jMenu_Cerrar_Sesion.setText("Cerrar Sesion");
        jMenu_Cerrar_Sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_Cerrar_SesionMouseClicked(evt);
            }
        });
        jMenu_Cerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Cerrar_SesionActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu_Cerrar_Sesion);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_Registrar_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Registrar_CompraActionPerformed
        RegistrarCompra NewCompra = new RegistrarCompra();
        NewCompra.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_Registrar_CompraActionPerformed

    private void Item_AgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_AgregarPedidoActionPerformed
        AgregarPedido AP = new AgregarPedido();
        AP.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_AgregarPedidoActionPerformed

    private void Item_Agregar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Agregar_ProductoActionPerformed
        AgregarProducto NewProd = new AgregarProducto();
        NewProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_Agregar_ProductoActionPerformed

    private void jMenu_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_PedidosActionPerformed
        Pedidos PD = new Pedidos();
        PD.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu_PedidosActionPerformed

    private void jMenu_Cerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Cerrar_SesionActionPerformed
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu_Cerrar_SesionActionPerformed

    private void jMenu_Cerrar_SesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_Cerrar_SesionMouseClicked
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu_Cerrar_SesionMouseClicked

    private void Item_Lista_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Lista_ComprasActionPerformed
        CompraInterfaz CI = new CompraInterfaz();
        CI.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_Lista_ComprasActionPerformed

    private void PedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidosMouseClicked
        try {
            int fila = Pedidos.getSelectedRow();
            int id = Integer.parseInt(Pedidos.getValueAt(fila, 0).toString());

            Connection connection = DriverManager.getConnection(url, username, password);
            ps = connection.prepareStatement("SELECT nom_client, id_pr, cantidad, fecha FROM pedidos WHERE id_pe=?");
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while (rs.next()) {
                IDPedido.setText(String.valueOf(id));
                IDPedido.setEditable(false);
                IDPedido.setEnabled(false);

                ClientePedido.setText(rs.getString("nom_client"));
                IDProducto.setText(rs.getString("id_pr"));
                Cantidad.setText(rs.getString("cantidad"));
                Fecha.setText(rs.getString("fecha"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_PedidosMouseClicked

    private void FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int id = Integer.parseInt(IDPedido.getText());
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("DELETE FROM pedidos WHERE id_pe=?");
            ps.setInt(1, id);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Pedido eliminado");
            cargarTabla();
            IDPedido.setText("");
            ClientePedido.setText("");
            IDProducto.setText("");
            Cantidad.setText("");
            Fecha.setText("");

        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_EliminarActionPerformed
    
    private void cargarInventario(int IDProducto){
       DefaultTableModel modeloTabla = (DefaultTableModel)Compras1.getModel();
       modeloTabla.setRowCount(0);
       
       int columnas;
       try{
           Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?");
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i<columnas; i++){
                    fila[i] =rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
       }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
       }  
   }
    
    private void cargarViejaCantidad(int IDProducto){
        try{
            cargarInventario(IDProducto);
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?"); 
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            
            while(rs.next()){
                CantidadTF.setText(rs.getString("stock"));
                CantidadTF.setEditable(false);
                CantidadTF.setEnabled(false);
                CantidadTF.setVisible(false);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
   }
    
     private void actualizarInventario(int IDProducto, int Cantidad){
       try{
           cargarViejaCantidad(IDProducto);
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ViejaCantidad = Integer.parseInt( CantidadTF.getText());

            ps= connection.prepareStatement("update inventario set stock= ? where id_pr = ?");
            int nuevaCantidad = ViejaCantidad - Cantidad;
            ps.setInt(1, nuevaCantidad);
            ps.setInt(2, IDProducto);
            ps.executeUpdate();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }  
       
   }
     
    private void CompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompletarActionPerformed
        int id = Integer.parseInt(IDPedido.getText());
        int IDPr = Integer.parseInt( IDProducto.getText());
        int Canti = Integer.parseInt(Cantidad.getText());
        /*****************************************/

        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("UPDATE pedidos SET completado = 1 WHERE id_pe=?");
            ps.setInt(1, id);
            ps.executeUpdate();
            //*******************************************************************
            actualizarInventario(IDPr,Canti);
            //********************************************************************
            JOptionPane.showMessageDialog(null, "Pedido Completado!");
            cargarTabla();
            IDPedido.setText("");
            ClientePedido.setText("");
            IDProducto.setText("");
            Cantidad.setText("");
            Fecha.setText("");

        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }//GEN-LAST:event_CompletarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int id = Integer.parseInt(IDPedido.getText());
        /*****************************************/
        String nombre = ClientePedido.getText();
        int IDPr = Integer.parseInt( IDProducto.getText());
        int Canti = Integer.parseInt(Cantidad.getText());
        String fecha= Fecha.getText();
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("UPDATE pedidos SET nom_client=?,id_pr=?,cantidad=?, fecha=? WHERE id_pe = ?");
            ps.setString(1, nombre);
            ps.setInt(2,IDPr );
            ps.setInt(3, Canti);
            ps.setString(4, fecha);
            ps.setInt(5, id);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro de pedido modificada");
            cargarTabla();
            IDPedido.setText("");
            ClientePedido.setText("");
            IDProducto.setText("");
            Cantidad.setText("");
            Fecha.setText("");  
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Item_Lista_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Lista_ProductosActionPerformed
        Inventario in = new Inventario();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_Lista_ProductosActionPerformed

    private void Item_Lista_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Lista_PedidosActionPerformed
        CompraInterfaz CI = new CompraInterfaz();
        CI.setVisible(true);
        dispose();
    }//GEN-LAST:event_Item_Lista_PedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField CantidadTF;
    private javax.swing.JTextField ClientePedido;
    private javax.swing.JButton Completar;
    private javax.swing.JTable Compras1;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Fecha;
    private javax.swing.JTextField IDPedido;
    private javax.swing.JTextField IDProducto;
    private javax.swing.JMenuItem Item_AgregarPedido;
    private javax.swing.JMenuItem Item_Agregar_Producto;
    private javax.swing.JMenuItem Item_Lista_Compras;
    private javax.swing.JMenuItem Item_Lista_Pedidos;
    private javax.swing.JMenuItem Item_Lista_Productos;
    private javax.swing.JMenuItem Item_Registrar_Compra;
    private javax.swing.JMenu JMenu_Inventario;
    private javax.swing.JTable Pedidos;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenu_Cerrar_Sesion;
    private javax.swing.JMenu jMenu_Compra;
    private javax.swing.JMenu jMenu_Pedidos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
