/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariojoyeriapoo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sara.Reyna
 */
public class RegistrarCompra extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCompra
     */
    public RegistrarCompra() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
    String url = "jdbc:mysql://localhost:3306/inventario_joyeria";
    String username = "root";
    /*String password = "Lechedefresa";*/
    String password = "$usanA198";
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    //Statement stm;
     int ViejaCantidad; 
     
   private void cargarInventario(int IDProducto){
       DefaultTableModel modeloTabla = (DefaultTableModel)Compras.getModel();
       modeloTabla.setRowCount(0);
       
       int columnas;
       try{
           
           Connection connection = DriverManager.getConnection(url,username,password);
            //ps= connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?");
            //ps.setInt(1, IDProducto);
            //Statement stm = connection.createStatement();
            /*
            ps = connection.prepareStatement("SELECT * FROM compras"); 
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            */
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?");
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i<columnas; i++){
                    fila[i] =rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
             
            //pasar estas dos ultimas lineas a otro metodo para poder 
            //despues llamar en el que estamos ahorita y asi re guardar 
            //lo que tenemos en la vieja cantidad
            //int f = Compras.getSelectedRow();
            //ViejaCantidad = Integer.parseInt(Compras.getValueAt(f, 0).toString());
            
       }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
       }  
   }
   
   private void cargarViejaCantidad(int IDProducto){
       
        try{
            int fila = Compras.getSelectedRow();
            int cantidad= Integer.parseInt(Compras.getValueAt(fila, 0).toString());
            
            cargarInventario(IDProducto);
            
            Connection connection = DriverManager.getConnection(url,username,password);
            ps = connection.prepareStatement("SELECT stock FROM inventario WHERE id_pr = ?"); 
            ps.setInt(1, IDProducto);
            rs = ps.executeQuery();
            
            while(rs.next()){
                TFIDCompra.setText(rs.getString("id_c"));
                TFIDCompra.setEditable(false);
                TFIDCompra.setEnabled(false);
                
                JtexNomCliCom.setText(rs.getString("id_pr"));
                ViejaCantidad.setText(rs.getString("stock"));
                JtexFechaCom.setText(rs.getString("fecha"));
            }
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
   }
   private void actualizarInventario(int IDProducto, int Cantidad){
       try{
           cargarViejaCantidad(IDProducto);
            Connection connection = DriverManager.getConnection(url,username,password);
            
            ps= connection.prepareStatement("update inventario set stock= ? where id_pr = ?");
            int nuevaCantidad = Cantidad+ ViejaCantidad;
            ps.setInt(1, nuevaCantidad);
            ps.setInt(2, IDProducto);
            ps.executeUpdate();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }  
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoMorado = new javax.swing.JPanel();
        TFNombreP = new javax.swing.JTextField();
        LabelNombreP = new javax.swing.JLabel();
        TFLabelPrecioP = new javax.swing.JTextField();
        PrecioP = new javax.swing.JLabel();
        BotonAgregarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Compras = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        JMenuInventario = new javax.swing.JMenu();
        ProductosITem = new javax.swing.JMenuItem();
        JMenuCompra = new javax.swing.JMenu();
        ListaComprasItem = new javax.swing.JMenuItem();
        NuevaCompraItem = new javax.swing.JMenuItem();
        NuevoProductoItem = new javax.swing.JMenuItem();
        JMenuPedidos = new javax.swing.JMenu();
        ListaPedidosItem = new javax.swing.JMenuItem();
        NuevoPedidoItem = new javax.swing.JMenuItem();
        JMenuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        FondoMorado.setBackground(new java.awt.Color(194, 196, 242));

        TFNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombrePActionPerformed(evt);
            }
        });

        LabelNombreP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNombreP.setText("ID del producto comprado:");

        TFLabelPrecioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLabelPrecioPActionPerformed(evt);
            }
        });

        PrecioP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrecioP.setText("Contidad comprada:");

        BotonAgregarP.setBackground(new java.awt.Color(113, 118, 217));
        BotonAgregarP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarP.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregarP.setText("Agregar");
        BotonAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRAR NUEVA COMPRA ");

        Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cantidad anterior"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Compras);
        if (Compras.getColumnModel().getColumnCount() > 0) {
            Compras.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout FondoMoradoLayout = new javax.swing.GroupLayout(FondoMorado);
        FondoMorado.setLayout(FondoMoradoLayout);
        FondoMoradoLayout.setHorizontalGroup(
            FondoMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMoradoLayout.createSequentialGroup()
                .addGroup(FondoMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoMoradoLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(BotonAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoMoradoLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoMoradoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(FondoMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelNombreP, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(PrecioP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(FondoMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFLabelPrecioP, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FondoMoradoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        FondoMoradoLayout.setVerticalGroup(
            FondoMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMoradoLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(FondoMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNombreP))
                .addGap(18, 18, 18)
                .addGroup(FondoMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFLabelPrecioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioP))
                .addGap(51, 51, 51)
                .addComponent(BotonAgregarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JMenuInventario.setText("Inventario");

        ProductosITem.setText("Lista de Productos");
        ProductosITem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosITemActionPerformed(evt);
            }
        });
        JMenuInventario.add(ProductosITem);

        MenuBar.add(JMenuInventario);

        JMenuCompra.setText("Compra");

        ListaComprasItem.setText("Listas de Compras");
        ListaComprasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaComprasItemActionPerformed(evt);
            }
        });
        JMenuCompra.add(ListaComprasItem);

        NuevaCompraItem.setText("Registrar nueva compra");
        NuevaCompraItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCompraItemActionPerformed(evt);
            }
        });
        JMenuCompra.add(NuevaCompraItem);

        NuevoProductoItem.setText("Agregar nuevo producto");
        NuevoProductoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoProductoItemActionPerformed(evt);
            }
        });
        JMenuCompra.add(NuevoProductoItem);

        MenuBar.add(JMenuCompra);

        JMenuPedidos.setText("Pedidos");

        ListaPedidosItem.setText("Lista de pedidos");
        ListaPedidosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaPedidosItemActionPerformed(evt);
            }
        });
        JMenuPedidos.add(ListaPedidosItem);

        NuevoPedidoItem.setText("Agregar Pedido");
        NuevoPedidoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPedidoItemActionPerformed(evt);
            }
        });
        JMenuPedidos.add(NuevoPedidoItem);

        MenuBar.add(JMenuPedidos);

        JMenuCerrarSesion.setText("Cerrar Sesion");
        JMenuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuCerrarSesionMouseClicked(evt);
            }
        });
        JMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCerrarSesionActionPerformed(evt);
            }
        });
        MenuBar.add(JMenuCerrarSesion);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(FondoMorado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FondoMorado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNombrePActionPerformed

    private void TFLabelPrecioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLabelPrecioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLabelPrecioPActionPerformed

    private void BotonAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarPActionPerformed
        // TODO add your handling code here:
        int IDProducto = Integer.parseInt( TFNombreP.getText());
        int Cantidad = Integer.parseInt(TFLabelPrecioP.getText());
        
        String timeStamp = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
     
        
        //ResultSet rs;
        //ResultSetMetaData rsmd;
        
        try{
            Connection connection = DriverManager.getConnection(url,username,password);
            ps= connection.prepareStatement("INSERT INTO compras (id_pr,cantidad, fecha) VALUES (?, ?, ?)");
            ps.setInt(1, IDProducto);
            ps.setInt(2, Cantidad);
            ps.setString(3, timeStamp);
            ps.executeUpdate();
            
            /***********************************************************************************/
            actualizarInventario(IDProducto,Cantidad);
            
            /**************************************************************************************/
            JOptionPane.showMessageDialog(null, "Registro guardado");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }            
    }//GEN-LAST:event_BotonAgregarPActionPerformed

    private void ProductosITemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosITemActionPerformed
        // TODO add your handling code here:
        Inventario in = new Inventario();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProductosITemActionPerformed

    private void NuevaCompraItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCompraItemActionPerformed
        // TODO add your handling code here:
        RegistrarCompra NewCompra = new RegistrarCompra();
        NewCompra.setVisible(true);
        dispose();
    }//GEN-LAST:event_NuevaCompraItemActionPerformed

    private void NuevoProductoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoProductoItemActionPerformed
        // TODO add your handling code here:
        AgregarProducto NewProd = new AgregarProducto();
        NewProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_NuevoProductoItemActionPerformed

    private void ListaPedidosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaPedidosItemActionPerformed
        // TODO add your handling code here:
        Pedidos PD = new Pedidos();
        PD.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListaPedidosItemActionPerformed

    private void NuevoPedidoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPedidoItemActionPerformed
        // TODO add your handling code here:
        AgregarCompra AP = new AgregarCompra();
        AP.setVisible(true);
        dispose();
    }//GEN-LAST:event_NuevoPedidoItemActionPerformed

    private void JMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCerrarSesionActionPerformed
        // TODO add your handling code here:
        
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_JMenuCerrarSesionActionPerformed

    private void JMenuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuCerrarSesionMouseClicked
        // TODO add your handling code here:
        InicioSesion IS = new InicioSesion();
        IS.setVisible(true);
        dispose();
    }//GEN-LAST:event_JMenuCerrarSesionMouseClicked

    private void ListaComprasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaComprasItemActionPerformed
        // TODO add your handling code here:
        CompraInterfaz CI = new CompraInterfaz();
        CI.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListaComprasItemActionPerformed

    private void ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasMouseClicked
        
    }//GEN-LAST:event_ComprasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarP;
    private javax.swing.JTable Compras;
    private javax.swing.JPanel FondoMorado;
    private javax.swing.JMenu JMenuCerrarSesion;
    private javax.swing.JMenu JMenuCompra;
    private javax.swing.JMenu JMenuInventario;
    private javax.swing.JMenu JMenuPedidos;
    private javax.swing.JLabel LabelNombreP;
    private javax.swing.JMenuItem ListaComprasItem;
    private javax.swing.JMenuItem ListaPedidosItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem NuevaCompraItem;
    private javax.swing.JMenuItem NuevoPedidoItem;
    private javax.swing.JMenuItem NuevoProductoItem;
    private javax.swing.JLabel PrecioP;
    private javax.swing.JMenuItem ProductosITem;
    private javax.swing.JTextField TFLabelPrecioP;
    private javax.swing.JTextField TFNombreP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
